title: Construction Connect Canada
description: Building connections in the construction industry
remote_theme: pages-themes/cayman@v0.2.0

author:
  name: Christopher Larsen
  email: contact@constructionconnect.ca

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Jekyll settings
markdown: kramdown
permalink: /:title/
