title: Construction Connect Canada
description: Building connections in the construction industry
theme: cayman

author:
  name: Christopher Larsen
  email: contact@constructionconnect.ca

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Jekyll settings
markdown: kramdown
permalink: /:title/
